logging:
  level:
    jp:
      co:
        g:
          japan: DEBUG
    org:
      springframework:
        security: DEBUG
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gseries?serverTimezone=Asia/Tokyo
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:templates/view/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  messages:
    basename: static/i18n/message
    encoding: UTF-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:META-INF/mybatis/dao/*DAO.xml

server:
  port: 8080